build:
    tags:
        - linux
        - nodejs
        - bower
        - dnsutils
        - ifstat
        - traceroute
        - libpam0g-dev
        - ng
    script:
        - npm install
        - npm run lint
        - npm test
        - npm run build

